name: 'Auto Label Action'
description: 'Add labels to Pull Request based on matched file patterns'
branding:
  icon: 'flag'
  color: 'gray-dark'
inputs:
  rules:
    description: 'PR Labeling rules, follows gitignore syntax'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
